export const VIRAL_SPOTS = [
  {
    id: 'pik-2',
    name: 'Pantai Pasir Putih PIK 2',
    region: 'Jakarta / Tangerang',
    description: 'Destinasi pesisir hits dengan pemandangan laut luas dan pantai berpasir putih bersih.',
    latitude: -6.0234,
    longitude: 106.6974,
    bestTime: 'Sore (Sunset)',
    icon: 'beach',
    tag: 'Coastal Cruise',
  },
  {
    id: 'kopi-daong',
    name: 'Kopi Daong',
    region: 'Bogor',
    description: 'Kedai kopi berkonsep alam di tengah hutan pinus rimbun dengan udara sejuk pegunungan.',
    latitude: -6.6931,
    longitude: 106.8458,
    bestTime: 'Sore - Malam',
    icon: 'coffee',
    tag: 'Mountain Pine',
  },
  {
    id: 'gunung-mas',
    name: 'Gunung Mas Puncak',
    region: 'Bogor',
    description: 'Agrowisata hamparan kebun teh hijau luas dengan jalanan berkelok khas rute Puncak.',
    latitude: -6.7022,
    longitude: 106.9881,
    bestTime: 'Pagi - Siang',
    icon: 'leaf',
    tag: 'Tea Highlands',
  },
  {
    id: 'kiara-artha',
    name: 'Kiara Artha Park',
    region: 'Bandung',
    description: 'Taman kota modern dengan atraksi air mancur menari yang memukau di malam hari.',
    latitude: -6.9142,
    longitude: 107.6358,
    bestTime: 'Sore - Malam',
    icon: 'fountain',
    tag: 'City Park',
  },
  {
    id: 'ciletuh',
    name: 'Geopark Ciletuh',
    region: 'Sukabumi',
    description: 'Situs warisan dunia dengan rute berkendara epik menyusuri tebing curam dan pantai selatan.',
    latitude: -7.1856,
    longitude: 106.4674,
    bestTime: 'Pagi - Sore',
    icon: 'terrain',
    tag: 'Epic Ride',
  },
  {
    id: 'tawangmangu',
    name: 'Candi Cetho & Tawangmangu',
    region: 'Karanganyar / Solo',
    description: 'Rute touring perbukitan Gunung Lawu dengan tikungan tajam dan pemandangan kebun teh melayang.',
    latitude: -7.5973,
    longitude: 111.1578,
    bestTime: 'Pagi - Sore',
    icon: 'image-filter-hdr',
    tag: 'Lawu Ridge',
  },
  {
    id: 'bromo',
    name: 'Penanjakan Gunung Bromo',
    region: 'Probolinggo / Malang',
    description: 'Lautan pasir berbisik dan pemandangan sunrise megah khas kaldera Tengger.',
    latitude: -7.9254,
    longitude: 112.9531,
    bestTime: 'Dini Hari (Sunrise)',
    icon: 'weather-sunset',
    tag: 'Volcano Sunrise',
  },
  {
    id: 'batu-malang',
    name: 'Paralayang Batu Malang',
    region: 'Malang / Batu',
    description: 'Puncak bukit tinggi dengan pemandangan citylight Kota Batu yang romantis di malam hari.',
    latitude: -7.8711,
    longitude: 112.4965,
    bestTime: 'Malam Hari',
    icon: 'city',
    tag: 'Night Lights',
  },
  {
    id: 'kintamani',
    name: 'Penelokan Kintamani',
    region: 'Bali',
    description: 'Teras pandang kaldera Gunung Batur dan Danau Batur dengan kabut tebal yang magis.',
    latitude: -8.2831,
    longitude: 115.3622,
    bestTime: 'Pagi Hari',
    icon: 'image-filter-hdr',
    tag: 'Volcano View',
  },
  {
    id: 'danau-toba',
    name: 'Tele Tower Danau Toba',
    region: 'Sumatra Utara',
    description: 'Menara pandang tertinggi untuk menyaksikan megahnya Danau Toba dan Pulau Samosir.',
    latitude: -2.5489,
    longitude: 98.6471,
    bestTime: 'Pagi - Siang',
    icon: 'ferry',
    tag: 'Lake Heritage',
  },
];
